# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from verity.v1 import brain_pb2 as verity_dot_v1_dot_brain__pb2
from verity.v1 import common_pb2 as verity_dot_v1_dot_common__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in verity/v1/brain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrainServiceStub:
    """Brain: Python orchestration service (chat, flows, offices, memory, providers).
    Called by the gateway only. Tenant identity comes from gRPC metadata.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/verity.v1.BrainService/Health',
                request_serializer=verity_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Hello = channel.unary_unary(
                '/verity.v1.BrainService/Hello',
                request_serializer=verity_dot_v1_dot_brain__pb2.HelloRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_brain__pb2.HelloResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.unary_stream(
                '/verity.v1.BrainService/ChatStream',
                request_serializer=verity_dot_v1_dot_brain__pb2.ChatRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_brain__pb2.ChatChunk.FromString,
                _registered_method=True)


class BrainServiceServicer:
    """Brain: Python orchestration service (chat, flows, offices, memory, providers).
    Called by the gateway only. Tenant identity comes from gRPC metadata.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hello(self, request, context):
        """M1 hello-path: gateway → brain round trip proving the spine.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request, context):
        """Chat streaming (M3). One request, server-streamed chunks; the gateway
        fans out to the client as SSE.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=verity_dot_v1_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=verity_dot_v1_dot_common__pb2.HealthResponse.SerializeToString,
            ),
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=verity_dot_v1_dot_brain__pb2.HelloRequest.FromString,
                    response_serializer=verity_dot_v1_dot_brain__pb2.HelloResponse.SerializeToString,
            ),
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=verity_dot_v1_dot_brain__pb2.ChatRequest.FromString,
                    response_serializer=verity_dot_v1_dot_brain__pb2.ChatChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verity.v1.BrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('verity.v1.BrainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrainService:
    """Brain: Python orchestration service (chat, flows, offices, memory, providers).
    Called by the gateway only. Tenant identity comes from gRPC metadata.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.BrainService/Health',
            verity_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
            verity_dot_v1_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.BrainService/Hello',
            verity_dot_v1_dot_brain__pb2.HelloRequest.SerializeToString,
            verity_dot_v1_dot_brain__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/verity.v1.BrainService/ChatStream',
            verity_dot_v1_dot_brain__pb2.ChatRequest.SerializeToString,
            verity_dot_v1_dot_brain__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
