# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: verity/v1/common.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'verity/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16verity/v1/common.proto\x12\tverity.v1\"@\n\tTenantCtx\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06org_id\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\"\xc2\x01\n\x0eHealthResponse\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .verity.v1.HealthResponse.Status\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x16\n\x0emissing_config\x18\x04 \x03(\t\"D\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x13\n\x0fSTATUS_DEGRADED\x10\x02\x42HZFgithub.com/electric13k/verity/packages/proto/gen/go/verity/v1;verityv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'verity.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/electric13k/verity/packages/proto/gen/go/verity/v1;verityv1'
  _globals['_TENANTCTX']._serialized_start=37
  _globals['_TENANTCTX']._serialized_end=101
  _globals['_HEALTHREQUEST']._serialized_start=103
  _globals['_HEALTHREQUEST']._serialized_end=118
  _globals['_HEALTHRESPONSE']._serialized_start=121
  _globals['_HEALTHRESPONSE']._serialized_end=315
  _globals['_HEALTHRESPONSE_STATUS']._serialized_start=247
  _globals['_HEALTHRESPONSE_STATUS']._serialized_end=315
# @@protoc_insertion_point(module_scope)
