# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: verity/v1/compute.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'verity/v1/compute.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from verity.v1 import common_pb2 as verity_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17verity/v1/compute.proto\x12\tverity.v1\x1a\x16verity/v1/common.proto\"1\n\x10SubmitJobRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\"9\n\x11SubmitJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x14\n\x0cwork_unit_id\x18\x02 \x01(\t\"E\n\x13RegisterNodeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08platform\x18\x02 \x01(\t\x12\x0e\n\x06models\x18\x03 \x03(\t\"\'\n\x14RegisterNodeResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"#\n\x10\x43laimWorkRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"Z\n\x11\x43laimWorkResponse\x12\x10\n\x08has_work\x18\x01 \x01(\x08\x12\x14\n\x0cwork_unit_id\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0e\n\x06prompt\x18\x04 \x01(\t\"L\n\x13SubmitResultRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x14\n\x0cwork_unit_id\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03 \x01(\t\"\'\n\x14SubmitResultResponse\x12\x0f\n\x07verdict\x18\x01 \x01(\t\"$\n\x11GetCreditsRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"%\n\x12GetCreditsResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x03\x32\xd0\x03\n\x12\x43oordinatorService\x12=\n\x06Health\x12\x18.verity.v1.HealthRequest\x1a\x19.verity.v1.HealthResponse\x12\x46\n\tSubmitJob\x12\x1b.verity.v1.SubmitJobRequest\x1a\x1c.verity.v1.SubmitJobResponse\x12O\n\x0cRegisterNode\x12\x1e.verity.v1.RegisterNodeRequest\x1a\x1f.verity.v1.RegisterNodeResponse\x12\x46\n\tClaimWork\x12\x1b.verity.v1.ClaimWorkRequest\x1a\x1c.verity.v1.ClaimWorkResponse\x12O\n\x0cSubmitResult\x12\x1e.verity.v1.SubmitResultRequest\x1a\x1f.verity.v1.SubmitResultResponse\x12I\n\nGetCredits\x12\x1c.verity.v1.GetCreditsRequest\x1a\x1d.verity.v1.GetCreditsResponseBHZFgithub.com/electric13k/verity/packages/proto/gen/go/verity/v1;verityv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'verity.v1.compute_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/electric13k/verity/packages/proto/gen/go/verity/v1;verityv1'
  _globals['_SUBMITJOBREQUEST']._serialized_start=62
  _globals['_SUBMITJOBREQUEST']._serialized_end=111
  _globals['_SUBMITJOBRESPONSE']._serialized_start=113
  _globals['_SUBMITJOBRESPONSE']._serialized_end=170
  _globals['_REGISTERNODEREQUEST']._serialized_start=172
  _globals['_REGISTERNODEREQUEST']._serialized_end=241
  _globals['_REGISTERNODERESPONSE']._serialized_start=243
  _globals['_REGISTERNODERESPONSE']._serialized_end=282
  _globals['_CLAIMWORKREQUEST']._serialized_start=284
  _globals['_CLAIMWORKREQUEST']._serialized_end=319
  _globals['_CLAIMWORKRESPONSE']._serialized_start=321
  _globals['_CLAIMWORKRESPONSE']._serialized_end=411
  _globals['_SUBMITRESULTREQUEST']._serialized_start=413
  _globals['_SUBMITRESULTREQUEST']._serialized_end=489
  _globals['_SUBMITRESULTRESPONSE']._serialized_start=491
  _globals['_SUBMITRESULTRESPONSE']._serialized_end=530
  _globals['_GETCREDITSREQUEST']._serialized_start=532
  _globals['_GETCREDITSREQUEST']._serialized_end=568
  _globals['_GETCREDITSRESPONSE']._serialized_start=570
  _globals['_GETCREDITSRESPONSE']._serialized_end=607
  _globals['_COORDINATORSERVICE']._serialized_start=610
  _globals['_COORDINATORSERVICE']._serialized_end=1074
# @@protoc_insertion_point(module_scope)
