# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from verity.v1 import common_pb2 as verity_dot_v1_dot_common__pb2
from verity.v1 import compute_pb2 as verity_dot_v1_dot_compute__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in verity/v1/compute_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorServiceStub:
    """Coordinator: the server-side surface of the scattered-compute network
    (M7). Lives in the Rust core service alongside the consensus verifier.

    Two audiences, one law: tenant / owner identity is ALWAYS taken from
    gateway-injected gRPC metadata (x-verity-user-id), NEVER from a request
    body. A node_id in a request body is only a handle; the coordinator binds
    every node operation to the owner in metadata and to the owner stored at
    registration, and fails closed when they disagree.

    User-facing (tenant = job owner):   SubmitJob
    Node-facing (owner = node owner):   RegisterNode, ClaimWork,
    SubmitResult, GetCredits

    Redundancy-2 + consensus: each work unit is assigned to exactly two nodes
    with DIFFERENT owners (sybil-pair guard, enforced at claim time). Honest
    nodes run temp-0 seed-7 inference, so byte-identical output is the
    consensus criterion. Agreement credits both nodes; disagreement credits
    neither and frees the unit for reassignment. Node output is UNTRUSTED
    external content: the coordinator only hashes it for comparison and never
    feeds it into a prompt.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/verity.v1.CoordinatorService/Health',
                request_serializer=verity_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.SubmitJob = channel.unary_unary(
                '/verity.v1.CoordinatorService/SubmitJob',
                request_serializer=verity_dot_v1_dot_compute__pb2.SubmitJobRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_compute__pb2.SubmitJobResponse.FromString,
                _registered_method=True)
        self.RegisterNode = channel.unary_unary(
                '/verity.v1.CoordinatorService/RegisterNode',
                request_serializer=verity_dot_v1_dot_compute__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_compute__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.ClaimWork = channel.unary_unary(
                '/verity.v1.CoordinatorService/ClaimWork',
                request_serializer=verity_dot_v1_dot_compute__pb2.ClaimWorkRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_compute__pb2.ClaimWorkResponse.FromString,
                _registered_method=True)
        self.SubmitResult = channel.unary_unary(
                '/verity.v1.CoordinatorService/SubmitResult',
                request_serializer=verity_dot_v1_dot_compute__pb2.SubmitResultRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_compute__pb2.SubmitResultResponse.FromString,
                _registered_method=True)
        self.GetCredits = channel.unary_unary(
                '/verity.v1.CoordinatorService/GetCredits',
                request_serializer=verity_dot_v1_dot_compute__pb2.GetCreditsRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_compute__pb2.GetCreditsResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer:
    """Coordinator: the server-side surface of the scattered-compute network
    (M7). Lives in the Rust core service alongside the consensus verifier.

    Two audiences, one law: tenant / owner identity is ALWAYS taken from
    gateway-injected gRPC metadata (x-verity-user-id), NEVER from a request
    body. A node_id in a request body is only a handle; the coordinator binds
    every node operation to the owner in metadata and to the owner stored at
    registration, and fails closed when they disagree.

    User-facing (tenant = job owner):   SubmitJob
    Node-facing (owner = node owner):   RegisterNode, ClaimWork,
    SubmitResult, GetCredits

    Redundancy-2 + consensus: each work unit is assigned to exactly two nodes
    with DIFFERENT owners (sybil-pair guard, enforced at claim time). Honest
    nodes run temp-0 seed-7 inference, so byte-identical output is the
    consensus criterion. Agreement credits both nodes; disagreement credits
    neither and frees the unit for reassignment. Node output is UNTRUSTED
    external content: the coordinator only hashes it for comparison and never
    feeds it into a prompt.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitJob(self, request, context):
        """User-facing: submit an inference job. Tenant (job owner) comes from
        metadata. Creates the job and its work unit(s).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterNode(self, request, context):
        """Node-facing: a volunteer daemon announces itself. Owner comes from
        metadata; the returned node_id is the handle used by later calls.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimWork(self, request, context):
        """Node-facing: claim one unit of work. The coordinator applies the
        redundancy-2 cap and the sybil-pair guard; may return has_work=false.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResult(self, request, context):
        """Node-facing: submit the deterministic output for a claimed unit. When
        both assignments are in, the coordinator runs consensus and writes the
        credit ledger.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCredits(self, request, context):
        """Node-facing: read the node's current credit balance (the credit
        acknowledgement the daemon polls for).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=verity_dot_v1_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=verity_dot_v1_dot_common__pb2.HealthResponse.SerializeToString,
            ),
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=verity_dot_v1_dot_compute__pb2.SubmitJobRequest.FromString,
                    response_serializer=verity_dot_v1_dot_compute__pb2.SubmitJobResponse.SerializeToString,
            ),
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=verity_dot_v1_dot_compute__pb2.RegisterNodeRequest.FromString,
                    response_serializer=verity_dot_v1_dot_compute__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'ClaimWork': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimWork,
                    request_deserializer=verity_dot_v1_dot_compute__pb2.ClaimWorkRequest.FromString,
                    response_serializer=verity_dot_v1_dot_compute__pb2.ClaimWorkResponse.SerializeToString,
            ),
            'SubmitResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitResult,
                    request_deserializer=verity_dot_v1_dot_compute__pb2.SubmitResultRequest.FromString,
                    response_serializer=verity_dot_v1_dot_compute__pb2.SubmitResultResponse.SerializeToString,
            ),
            'GetCredits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredits,
                    request_deserializer=verity_dot_v1_dot_compute__pb2.GetCreditsRequest.FromString,
                    response_serializer=verity_dot_v1_dot_compute__pb2.GetCreditsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verity.v1.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('verity.v1.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService:
    """Coordinator: the server-side surface of the scattered-compute network
    (M7). Lives in the Rust core service alongside the consensus verifier.

    Two audiences, one law: tenant / owner identity is ALWAYS taken from
    gateway-injected gRPC metadata (x-verity-user-id), NEVER from a request
    body. A node_id in a request body is only a handle; the coordinator binds
    every node operation to the owner in metadata and to the owner stored at
    registration, and fails closed when they disagree.

    User-facing (tenant = job owner):   SubmitJob
    Node-facing (owner = node owner):   RegisterNode, ClaimWork,
    SubmitResult, GetCredits

    Redundancy-2 + consensus: each work unit is assigned to exactly two nodes
    with DIFFERENT owners (sybil-pair guard, enforced at claim time). Honest
    nodes run temp-0 seed-7 inference, so byte-identical output is the
    consensus criterion. Agreement credits both nodes; disagreement credits
    neither and frees the unit for reassignment. Node output is UNTRUSTED
    external content: the coordinator only hashes it for comparison and never
    feeds it into a prompt.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.CoordinatorService/Health',
            verity_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
            verity_dot_v1_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.CoordinatorService/SubmitJob',
            verity_dot_v1_dot_compute__pb2.SubmitJobRequest.SerializeToString,
            verity_dot_v1_dot_compute__pb2.SubmitJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.CoordinatorService/RegisterNode',
            verity_dot_v1_dot_compute__pb2.RegisterNodeRequest.SerializeToString,
            verity_dot_v1_dot_compute__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.CoordinatorService/ClaimWork',
            verity_dot_v1_dot_compute__pb2.ClaimWorkRequest.SerializeToString,
            verity_dot_v1_dot_compute__pb2.ClaimWorkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.CoordinatorService/SubmitResult',
            verity_dot_v1_dot_compute__pb2.SubmitResultRequest.SerializeToString,
            verity_dot_v1_dot_compute__pb2.SubmitResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCredits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.CoordinatorService/GetCredits',
            verity_dot_v1_dot_compute__pb2.GetCreditsRequest.SerializeToString,
            verity_dot_v1_dot_compute__pb2.GetCreditsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
