# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from verity.v1 import common_pb2 as verity_dot_v1_dot_common__pb2
from verity.v1 import core_pb2 as verity_dot_v1_dot_core__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in verity/v1/core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreServiceStub:
    """Core: Rust service — Qdrant vector search proxy, embedding pipelines,
    consensus verification. Every vector query carries a mandatory payload
    filter user_id == tenant_ctx.user_id, constructed in this service from
    gRPC metadata ONLY (never from request bodies).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/verity.v1.CoreService/Health',
                request_serializer=verity_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Echo = channel.unary_unary(
                '/verity.v1.CoreService/Echo',
                request_serializer=verity_dot_v1_dot_core__pb2.EchoRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_core__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.VectorSearch = channel.unary_unary(
                '/verity.v1.CoreService/VectorSearch',
                request_serializer=verity_dot_v1_dot_core__pb2.VectorSearchRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_core__pb2.VectorSearchResponse.FromString,
                _registered_method=True)


class CoreServiceServicer:
    """Core: Rust service — Qdrant vector search proxy, embedding pipelines,
    consensus verification. Every vector query carries a mandatory payload
    filter user_id == tenant_ctx.user_id, constructed in this service from
    gRPC metadata ONLY (never from request bodies).
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Echo(self, request, context):
        """M1 hello-path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorSearch(self, request, context):
        """Vector search (M3). collection is a logical name; tenant filter is
        applied server-side unconditionally.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=verity_dot_v1_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=verity_dot_v1_dot_common__pb2.HealthResponse.SerializeToString,
            ),
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=verity_dot_v1_dot_core__pb2.EchoRequest.FromString,
                    response_serializer=verity_dot_v1_dot_core__pb2.EchoResponse.SerializeToString,
            ),
            'VectorSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.VectorSearch,
                    request_deserializer=verity_dot_v1_dot_core__pb2.VectorSearchRequest.FromString,
                    response_serializer=verity_dot_v1_dot_core__pb2.VectorSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verity.v1.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('verity.v1.CoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreService:
    """Core: Rust service — Qdrant vector search proxy, embedding pipelines,
    consensus verification. Every vector query carries a mandatory payload
    filter user_id == tenant_ctx.user_id, constructed in this service from
    gRPC metadata ONLY (never from request bodies).
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.CoreService/Health',
            verity_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
            verity_dot_v1_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.CoreService/Echo',
            verity_dot_v1_dot_core__pb2.EchoRequest.SerializeToString,
            verity_dot_v1_dot_core__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VectorSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.CoreService/VectorSearch',
            verity_dot_v1_dot_core__pb2.VectorSearchRequest.SerializeToString,
            verity_dot_v1_dot_core__pb2.VectorSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
