# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: verity/v1/core.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'verity/v1/core.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from verity.v1 import common_pb2 as verity_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14verity/v1/core.proto\x12\tverity.v1\x1a\x16verity/v1/common.proto\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"H\n\x13VectorSearchRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\x12\r\n\x05limit\x18\x03 \x01(\r\">\n\x14VectorSearchResponse\x12&\n\x06points\x18\x01 \x03(\x0b\x32\x16.verity.v1.ScoredPoint\">\n\x0bScoredPoint\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x14\n\x0cpayload_json\x18\x03 \x01(\t2\xd6\x01\n\x0b\x43oreService\x12=\n\x06Health\x12\x18.verity.v1.HealthRequest\x1a\x19.verity.v1.HealthResponse\x12\x37\n\x04\x45\x63ho\x12\x16.verity.v1.EchoRequest\x1a\x17.verity.v1.EchoResponse\x12O\n\x0cVectorSearch\x12\x1e.verity.v1.VectorSearchRequest\x1a\x1f.verity.v1.VectorSearchResponseBHZFgithub.com/electric13k/verity/packages/proto/gen/go/verity/v1;verityv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'verity.v1.core_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/electric13k/verity/packages/proto/gen/go/verity/v1;verityv1'
  _globals['_ECHOREQUEST']._serialized_start=59
  _globals['_ECHOREQUEST']._serialized_end=89
  _globals['_ECHORESPONSE']._serialized_start=91
  _globals['_ECHORESPONSE']._serialized_end=122
  _globals['_VECTORSEARCHREQUEST']._serialized_start=124
  _globals['_VECTORSEARCHREQUEST']._serialized_end=196
  _globals['_VECTORSEARCHRESPONSE']._serialized_start=198
  _globals['_VECTORSEARCHRESPONSE']._serialized_end=260
  _globals['_SCOREDPOINT']._serialized_start=262
  _globals['_SCOREDPOINT']._serialized_end=324
  _globals['_CORESERVICE']._serialized_start=327
  _globals['_CORESERVICE']._serialized_end=541
# @@protoc_insertion_point(module_scope)
