# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from verity.v1 import platform_pb2 as verity_dot_v1_dot_platform__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in verity/v1/platform_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlatformServiceStub:
    """Platform: the persistence & platform surface of the Python brain
    (conversations, provider keys, offices, skills, MCP, upload, branching).
    Registered on the same brain gRPC server; called by the gateway only.
    Tenant identity comes from gRPC metadata (x-verity-user-id) — never from a
    request body. Every repo query filters by that user id and fails closed.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListConversations = channel.unary_unary(
                '/verity.v1.PlatformService/ListConversations',
                request_serializer=verity_dot_v1_dot_platform__pb2.ListConversationsRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.ListConversationsResponse.FromString,
                _registered_method=True)
        self.CreateConversation = channel.unary_unary(
                '/verity.v1.PlatformService/CreateConversation',
                request_serializer=verity_dot_v1_dot_platform__pb2.CreateConversationRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.Conversation.FromString,
                _registered_method=True)
        self.GetConversation = channel.unary_unary(
                '/verity.v1.PlatformService/GetConversation',
                request_serializer=verity_dot_v1_dot_platform__pb2.IdRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.ConversationDetail.FromString,
                _registered_method=True)
        self.UpdateConversation = channel.unary_unary(
                '/verity.v1.PlatformService/UpdateConversation',
                request_serializer=verity_dot_v1_dot_platform__pb2.UpdateConversationRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.Conversation.FromString,
                _registered_method=True)
        self.DeleteConversation = channel.unary_unary(
                '/verity.v1.PlatformService/DeleteConversation',
                request_serializer=verity_dot_v1_dot_platform__pb2.IdRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.Empty.FromString,
                _registered_method=True)
        self.ListProviderKeys = channel.unary_unary(
                '/verity.v1.PlatformService/ListProviderKeys',
                request_serializer=verity_dot_v1_dot_platform__pb2.Empty.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.ProviderKeysResponse.FromString,
                _registered_method=True)
        self.PutProviderKey = channel.unary_unary(
                '/verity.v1.PlatformService/PutProviderKey',
                request_serializer=verity_dot_v1_dot_platform__pb2.PutProviderKeyRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.ProviderKeyStatus.FromString,
                _registered_method=True)
        self.DeleteProviderKey = channel.unary_unary(
                '/verity.v1.PlatformService/DeleteProviderKey',
                request_serializer=verity_dot_v1_dot_platform__pb2.ProviderRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.Empty.FromString,
                _registered_method=True)
        self.GetMe = channel.unary_unary(
                '/verity.v1.PlatformService/GetMe',
                request_serializer=verity_dot_v1_dot_platform__pb2.Empty.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.MeResponse.FromString,
                _registered_method=True)
        self.ListOffices = channel.unary_unary(
                '/verity.v1.PlatformService/ListOffices',
                request_serializer=verity_dot_v1_dot_platform__pb2.Empty.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.OfficesResponse.FromString,
                _registered_method=True)
        self.CreateOffice = channel.unary_unary(
                '/verity.v1.PlatformService/CreateOffice',
                request_serializer=verity_dot_v1_dot_platform__pb2.CreateOfficeRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.Office.FromString,
                _registered_method=True)
        self.RunOffice = channel.unary_unary(
                '/verity.v1.PlatformService/RunOffice',
                request_serializer=verity_dot_v1_dot_platform__pb2.IdRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.RunOfficeResponse.FromString,
                _registered_method=True)
        self.GetOfficeRun = channel.unary_unary(
                '/verity.v1.PlatformService/GetOfficeRun',
                request_serializer=verity_dot_v1_dot_platform__pb2.GetOfficeRunRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.OfficeRunDetail.FromString,
                _registered_method=True)
        self.ListSkills = channel.unary_unary(
                '/verity.v1.PlatformService/ListSkills',
                request_serializer=verity_dot_v1_dot_platform__pb2.Empty.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.SkillsResponse.FromString,
                _registered_method=True)
        self.ListMcpServers = channel.unary_unary(
                '/verity.v1.PlatformService/ListMcpServers',
                request_serializer=verity_dot_v1_dot_platform__pb2.Empty.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.McpServersResponse.FromString,
                _registered_method=True)
        self.CreateMcpServer = channel.unary_unary(
                '/verity.v1.PlatformService/CreateMcpServer',
                request_serializer=verity_dot_v1_dot_platform__pb2.CreateMcpServerRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.McpServer.FromString,
                _registered_method=True)
        self.McpCall = channel.unary_unary(
                '/verity.v1.PlatformService/McpCall',
                request_serializer=verity_dot_v1_dot_platform__pb2.McpCallRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.McpCallResponse.FromString,
                _registered_method=True)
        self.UploadFile = channel.unary_unary(
                '/verity.v1.PlatformService/UploadFile',
                request_serializer=verity_dot_v1_dot_platform__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.UploadFileResponse.FromString,
                _registered_method=True)
        self.CreateBranch = channel.unary_unary(
                '/verity.v1.PlatformService/CreateBranch',
                request_serializer=verity_dot_v1_dot_platform__pb2.CreateBranchRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.CreateBranchResponse.FromString,
                _registered_method=True)
        self.GetTranscript = channel.unary_unary(
                '/verity.v1.PlatformService/GetTranscript',
                request_serializer=verity_dot_v1_dot_platform__pb2.TranscriptRequest.SerializeToString,
                response_deserializer=verity_dot_v1_dot_platform__pb2.TranscriptResponse.FromString,
                _registered_method=True)


class PlatformServiceServicer:
    """Platform: the persistence & platform surface of the Python brain
    (conversations, provider keys, offices, skills, MCP, upload, branching).
    Registered on the same brain gRPC server; called by the gateway only.
    Tenant identity comes from gRPC metadata (x-verity-user-id) — never from a
    request body. Every repo query filters by that user id and fails closed.
    """

    def ListConversations(self, request, context):
        """--- Conversations (P2) ------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProviderKeys(self, request, context):
        """--- Provider keys (P3) ------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutProviderKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProviderKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOffices(self, request, context):
        """--- Offices (P4) ------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOffice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunOffice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOfficeRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSkills(self, request, context):
        """--- Skills (P5) -------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMcpServers(self, request, context):
        """--- MCP (P5) ----------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMcpServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def McpCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request, context):
        """--- Upload (P6) -------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBranch(self, request, context):
        """--- Branching (P7) ----------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTranscript(self, request, context):
        """--- Transcripts (P7) --------------------------------------------------
        PUBLIC read-only. Keyed by an unguessable share id (the bearer capability)
        — NO tenant metadata is consulted, so the gateway serves it without auth.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlatformServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConversations,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.ListConversationsRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.ListConversationsResponse.SerializeToString,
            ),
            'CreateConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConversation,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.CreateConversationRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.Conversation.SerializeToString,
            ),
            'GetConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversation,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.IdRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.ConversationDetail.SerializeToString,
            ),
            'UpdateConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConversation,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.UpdateConversationRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.Conversation.SerializeToString,
            ),
            'DeleteConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConversation,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.IdRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.Empty.SerializeToString,
            ),
            'ListProviderKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviderKeys,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.Empty.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.ProviderKeysResponse.SerializeToString,
            ),
            'PutProviderKey': grpc.unary_unary_rpc_method_handler(
                    servicer.PutProviderKey,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.PutProviderKeyRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.ProviderKeyStatus.SerializeToString,
            ),
            'DeleteProviderKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProviderKey,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.ProviderRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.Empty.SerializeToString,
            ),
            'GetMe': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMe,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.Empty.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.MeResponse.SerializeToString,
            ),
            'ListOffices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOffices,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.Empty.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.OfficesResponse.SerializeToString,
            ),
            'CreateOffice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOffice,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.CreateOfficeRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.Office.SerializeToString,
            ),
            'RunOffice': grpc.unary_unary_rpc_method_handler(
                    servicer.RunOffice,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.IdRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.RunOfficeResponse.SerializeToString,
            ),
            'GetOfficeRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOfficeRun,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.GetOfficeRunRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.OfficeRunDetail.SerializeToString,
            ),
            'ListSkills': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSkills,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.Empty.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.SkillsResponse.SerializeToString,
            ),
            'ListMcpServers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMcpServers,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.Empty.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.McpServersResponse.SerializeToString,
            ),
            'CreateMcpServer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMcpServer,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.CreateMcpServerRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.McpServer.SerializeToString,
            ),
            'McpCall': grpc.unary_unary_rpc_method_handler(
                    servicer.McpCall,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.McpCallRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.McpCallResponse.SerializeToString,
            ),
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.UploadFileRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.UploadFileResponse.SerializeToString,
            ),
            'CreateBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBranch,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.CreateBranchRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.CreateBranchResponse.SerializeToString,
            ),
            'GetTranscript': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTranscript,
                    request_deserializer=verity_dot_v1_dot_platform__pb2.TranscriptRequest.FromString,
                    response_serializer=verity_dot_v1_dot_platform__pb2.TranscriptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verity.v1.PlatformService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('verity.v1.PlatformService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlatformService:
    """Platform: the persistence & platform surface of the Python brain
    (conversations, provider keys, offices, skills, MCP, upload, branching).
    Registered on the same brain gRPC server; called by the gateway only.
    Tenant identity comes from gRPC metadata (x-verity-user-id) — never from a
    request body. Every repo query filters by that user id and fails closed.
    """

    @staticmethod
    def ListConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/ListConversations',
            verity_dot_v1_dot_platform__pb2.ListConversationsRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.ListConversationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/CreateConversation',
            verity_dot_v1_dot_platform__pb2.CreateConversationRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.Conversation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/GetConversation',
            verity_dot_v1_dot_platform__pb2.IdRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.ConversationDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/UpdateConversation',
            verity_dot_v1_dot_platform__pb2.UpdateConversationRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.Conversation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/DeleteConversation',
            verity_dot_v1_dot_platform__pb2.IdRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProviderKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/ListProviderKeys',
            verity_dot_v1_dot_platform__pb2.Empty.SerializeToString,
            verity_dot_v1_dot_platform__pb2.ProviderKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutProviderKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/PutProviderKey',
            verity_dot_v1_dot_platform__pb2.PutProviderKeyRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.ProviderKeyStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProviderKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/DeleteProviderKey',
            verity_dot_v1_dot_platform__pb2.ProviderRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/GetMe',
            verity_dot_v1_dot_platform__pb2.Empty.SerializeToString,
            verity_dot_v1_dot_platform__pb2.MeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOffices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/ListOffices',
            verity_dot_v1_dot_platform__pb2.Empty.SerializeToString,
            verity_dot_v1_dot_platform__pb2.OfficesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOffice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/CreateOffice',
            verity_dot_v1_dot_platform__pb2.CreateOfficeRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.Office.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunOffice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/RunOffice',
            verity_dot_v1_dot_platform__pb2.IdRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.RunOfficeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOfficeRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/GetOfficeRun',
            verity_dot_v1_dot_platform__pb2.GetOfficeRunRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.OfficeRunDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSkills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/ListSkills',
            verity_dot_v1_dot_platform__pb2.Empty.SerializeToString,
            verity_dot_v1_dot_platform__pb2.SkillsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMcpServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/ListMcpServers',
            verity_dot_v1_dot_platform__pb2.Empty.SerializeToString,
            verity_dot_v1_dot_platform__pb2.McpServersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMcpServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/CreateMcpServer',
            verity_dot_v1_dot_platform__pb2.CreateMcpServerRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.McpServer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def McpCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/McpCall',
            verity_dot_v1_dot_platform__pb2.McpCallRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.McpCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/UploadFile',
            verity_dot_v1_dot_platform__pb2.UploadFileRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.UploadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/CreateBranch',
            verity_dot_v1_dot_platform__pb2.CreateBranchRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.CreateBranchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verity.v1.PlatformService/GetTranscript',
            verity_dot_v1_dot_platform__pb2.TranscriptRequest.SerializeToString,
            verity_dot_v1_dot_platform__pb2.TranscriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
