#!/usr/bin/env node
// Generates CSS custom properties from tokens.json.
// Output: dist/tokens.css — :root (light), [data-theme="dark"], and
// prefers-color-scheme fallback. Figma variable sync consumes tokens.json
// directly (M4, needs Figma auth).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(readFileSync(join(here, "tokens.json"), "utf8"));

const colorVars = (theme) =>
  Object.entries(tokens.color)
    .map(([name, v]) => `  --v-${name}: ${v[theme]};`)
    .join("\n");

const spaceVars = Object.entries(tokens.space)
  .filter(([k]) => k !== "rule")
  .map(([k, v]) => `  --v-space-${k}: ${v};`)
  .join("\n");

const radiusVars = Object.entries(tokens.radius)
  .map(([k, v]) => `  --v-radius-${k}: ${v};`)
  .join("\n");

const motionVars = Object.entries(tokens.motion)
  .filter(([k]) => k !== "rule")
  .map(([k, v]) => `  --v-motion-${k}: ${v};`)
  .join("\n");

const fontVars = Object.entries(tokens.font)
  .map(([k, v]) => `  --v-font-${k}: "${v.family}";`)
  .join("\n");

const css = `/* Generated by packages/tokens/build.mjs — do not edit by hand. */
:root {
${colorVars("light")}
${spaceVars}
${radiusVars}
${motionVars}
${fontVars}
  color-scheme: light dark;
}

[data-theme="dark"] {
${colorVars("dark")}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${colorVars("dark").replace(/^ {2}/gm, "    ")}
  }
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --v-motion-fast: 0ms;
    --v-motion-base: 0ms;
    --v-motion-slow: 0ms;
  }
}
`;

mkdirSync(join(here, "dist"), { recursive: true });
writeFileSync(join(here, "dist", "tokens.css"), css);
console.log("tokens.css written:", Object.keys(tokens.color).length, "colors, light+dark");
